### ISSUE TITLE
FR: Glob blacklist dirs, add whitelist dirs

### ISSUE THREAD

**Issue by patmaddox** [thought-machine/please#3293]
I have a repo that pulls in lots of dirs named `*.jj` and `*.git` - sometimes these include `BUILD` files that are invalid for please. I would like please to support globbing blacklist dirs, and allowing whitelist dirs. Currently, [please only works on fixed paths](https://github.com/thought-machine/please/blob/0e4a934737c376dddd62ee39c8cf90c2a5e2af65/src/plz/plz.go#L213).

This would support a "default deny" workflow, while still permitting specific dirs.

I am up for trying to implement this, and want to start the discussion.

```toml
[parse]
blacklistdirs = "**/*.git"
blacklistdirs = "**/*.jj"

whitelistdirs = "important-project.git"
whitelistdirs = "important-projects/*.jj"
```
